### ISSUE TITLE
Memory problems when updating to GHC 9.2.1-alpha2

### ISSUE THREAD

**Issue by noughtmare** [ekmett/unlifted#2]
I just wanted to let you know that I've opened [a GHC issue](https://gitlab.haskell.org/ghc/ghc/-/issues/19744) after encountering memory usage issues while updating this package to GHC 9.2.1-alpha2. The update commit is here: https://github.com/noughtmare/unboxed/commit/b6338e68540a2c62a6aae6ded0dcdc3b83106916.

**Comment by ekmett** [comment]
Appears fixed in 9.4.1.
